name: deploy to aws s3 and invalidate cf cache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Configure AWS credentials once for all later steps
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Sync files to S3
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude ".gitignore" \
            --exclude ".git/*" \
            --delete

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2.4.2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: us-east-1